server:
  port: 12000
spring:
  application:
    name: tensquare‐config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangshun0529/tensquare-config.git
  rabbitmq:
    host: 47.96.141.125
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh