server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.141.125:3306/tensquare_recruit?characterEncoding=UTF-8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
